In [61]:
import pandas as pd
import numpy as np

df=pd.read_csv('./merged_info.csv')

df
# "Mar de la Vida OJSC",
# "979893388",
# "Oceanfront Oasis Inc Carriers",
# "8327"

,Unnamed: 0,link_type,weight,dataset_x,source,target,key,source_type,source_country,target_type,target_country
0,0,ownership,0.900140,MC1,Spanish Shrimp Carriers,12744,0,company,Nalakond,organization,NaN
1,1,partnership,0.845897,MC1,Spanish Shrimp Carriers,21323516,0,company,Nalakond,organization,NaN
2,2,partnership,0.964876,MC1,Spanish Shrimp Carriers,290834957,0,company,Nalakond,organization,NaN
3,3,ownership,0.964213,MC1,Spanish Shrimp Carriers,3506021,0,company,Nalakond,organization,NaN
4,4,family_relationship,0.823486,MC1,Spanish Shrimp Carriers,Conventionâ,0,company,Nalakond,unknown,NaN
...,...,...,...,...,...,...,...,...,...,...,...
11064,11064,family_relationship,0.817772,MC1,Ocano del Este SE,Mary Clements,0,unknown,NaN,person,Country_271835
11065,11065,partnership,0.873537,MC1,Norwegian Shrimp N.V. -,67261634,0,unknown,NaN,organization,NaN
11066,11066,partnership,0.849333,MC1,Norwegian Shrimp N.V. -,344,0,unknown,NaN,organization,NaN
11067,11067,membership,0.814217,MC1,Malabar Sea Catch Sp,672,0,unknown,NaN,organization,NaN
11068,11068,membership,0.823890,MC1,Malabar Sea Catch Sp,449820,0,unknown,NaN,organization,NaN

# Ownership

In [62]:
arr1 = np.zeros((9,9))
o_table=pd.DataFrame(arr1, columns=['company_s', 'event_s', 'location_s', 'movement_s', 'organization_s', 'person_s', 'political_organization_s', 'vessel_s', 'unknown_s'],index=['company_t', 'event_t', 'location_t', 'movement_t', 'organization_t', 'person_t', 'political_organization_t', 'vessel_t', 'unknown_t'])

o_table_4points=pd.DataFrame(columns=['company_s', 'event_s', 'location_s', 'movement_s', 'organization_s', 'person_s', 'political_organization_s', 'vessel_s', 'unknown_s'],index=['company_t', 'event_t', 'location_t', 'movement_t', 'organization_t', 'person_t', 'political_organization_t', 'vessel_t', 'unknown_t'])
o_table_4points['organization_s'] = 0
o_table_4points['unknown_s'] = 0
o_table_4points.iloc[4] = 0
o_table_4points.iloc[8] = 0

o_cnt = 0

In [63]:
collect_4points = pd.DataFrame()
for row in df.iterrows():
    # print(row[1][1],row[1][7],row[1][9])
    if row[1][1] == 'ownership':
        o_cnt = o_cnt + 1
        o_table[row[1][7]+'_s'][row[1][9]+'_t'] = o_table[row[1][7]+'_s'][row[1][9]+'_t'] + 1

        if (row[1][4] == 'Mar de la Vida OJSC') or (row[1][5] == 'Mar de la Vida OJSC') or (row[1][4] == '979893388') or (row[1][5] == '979893388') or (row[1][4] == 'Oceanfront Oasis Inc Carriers') or (row[1][5] == 'Oceanfront Oasis Inc Carriers') or (row[1][4] == '8327') or (row[1][5] == '8327'):
            collect_4points = collect_4points.append(row[1])
            o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
# 可疑点存在的边
collect_4points

/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2958558573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = o_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1

,Unnamed: 0,link_type,weight,dataset_x,source,target,key,source_type,source_country,target_type,target_country
868,868,ownership,0.817322,MC1,9,979893388,0,organization,NaN,organization,NaN
1315,1315,ownership,0.903510,MC1,f21800ca-b3c9-404b-8438-3d75ea84c409,979893388,0,location,NaN,organization,NaN
2083,2083,ownership,0.834928,MC1,34,979893388,0,organization,NaN,organization,NaN
2327,2327,ownership,0.813712,MC1,Mar del Oeste Pic,979893388,1,company,Vesperlandia,organization,NaN
2415,2415,ownership,0.891332,MC1,8327,weeks,0,organization,NaN,movement,NaN
2416,2416,ownership,0.824839,MC1,8327,40213337,0,organization,NaN,organization,NaN
2417,2417,ownership,0.907795,MC1,8327,cutters,0,organization,NaN,vessel,NaN
2458,2458,ownership,0.823488,MC1,Coast,8327,0,vessel,NaN,organization,NaN
4022,4022,ownership,0.804815,MC1,17c99d9d-7049-4ebb-8a2a-f3d39cc42870,979893388,0,location,NaN,organization,NaN
4315,4315,ownership,0.838258,MC1,Christopher Peterson,979893388,0,person,Oceanus,organization,NaN
4960,4960,ownership,0.836394,MC1,979893388,Oceanfront Oasis Inc Carriers,0,organization,NaN,unknown,NaN
4969,4969,ownership,0.873781,MC1,979893388,990,0,organization,NaN,organization,NaN
4972,4972,ownership,0.924564,MC1,979893388,Kristin Jones,0,organization,NaN,person,Country_271835
4998,4998,ownership,0.863397,MC1,979893388,Ryabikova,0,organization,NaN,unknown,NaN
4999,4999,ownership,0.847196,MC1,979893388,Erica Hamilton,0,organization,NaN,person,Marebak
5010,5010,ownership,0.824144,MC1,979893388,John Barnes DDS,0,organization,NaN,person,Country_271835
5012,5012,ownership,0.813831,MC1,979893388,brianbushard,0,organization,NaN,unknown,NaN
5016,5016,ownership,0.814809,MC1,979893388,Miranda Long,0,organization,NaN,person,Country_271835
5030,5030,ownership,0.826820,MC1,979893388,ROBYN BECK,0,organization,NaN,unknown,NaN
5031,5031,ownership,0.884165,MC1,979893388,13d79d632036,0,organization,NaN,unknown,NaN
5149,5149,ownership,0.859340,MC1,1972868,979893388,0,organization,NaN,organization,NaN
5344,5344,ownership,0.850426,MC1,9590898,979893388,0,organization,NaN,organization,NaN
5346,5346,ownership,0.835931,MC1,Joshua Garrett,979893388,0,person,Arreciviento,organization,NaN
7416,7416,ownership,0.890057,MC1,Erica Hamilton,979893388,0,person,Marebak,organization,NaN
8023,8023,ownership,0.819125,MC1,9345,979893388,0,political_organization,NaN,organization,NaN
10135,10135,ownership,0.838920,MC1,Ocean Fisheries Llc,979893388,0,unknown,NaN,organization,NaN
10469,10469,ownership,0.811119,MC1,Mar de la Vida OJSC,Jon White,0,unknown,NaN,person,Polarisdom
10532,10532,ownership,0.118600,MC1,Seabreeze Foods Ltd. Corporation United,8327,0,unknown,NaN,organization,NaN

In [64]:
# 个数
o_table

,company_s,event_s,location_s,movement_s,organization_s,person_s,political_organization_s,vessel_s,unknown_s
company_t,12.0,3.0,17.0,3.0,44.0,20.0,5.0,2.0,30.0
event_t,3.0,4.0,3.0,2.0,7.0,14.0,1.0,0.0,9.0
location_t,18.0,6.0,25.0,9.0,49.0,27.0,8.0,2.0,38.0
movement_t,5.0,0.0,2.0,4.0,3.0,6.0,0.0,2.0,0.0
organization_t,55.0,9.0,66.0,5.0,289.0,87.0,33.0,19.0,111.0
person_t,60.0,11.0,62.0,9.0,137.0,0.0,31.0,13.0,82.0
political_organization_t,4.0,0.0,10.0,1.0,16.0,11.0,10.0,0.0,7.0
vessel_t,2.0,0.0,7.0,0.0,17.0,9.0,0.0,12.0,6.0
unknown_t,48.0,4.0,35.0,1.0,142.0,81.0,7.0,6.0,82.0

In [65]:
# 个数
o_table_4points

,company_s,event_s,location_s,movement_s,organization_s,person_s,political_organization_s,vessel_s,unknown_s
company_t,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0
event_t,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0
location_t,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0
movement_t,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,0
organization_t,1,0,2,0,6,3,1,1,2
person_t,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,1
political_organization_t,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0
vessel_t,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,0
unknown_t,0,0,0,0,5,0,0,0,0

In [66]:
# 总数
print(o_cnt)

1980

In [67]:
# 比例
o_table=(o_table/11069) * 100
o_table

,company_s,event_s,location_s,movement_s,organization_s,person_s,political_organization_s,vessel_s,unknown_s
company_t,0.108411,0.027103,0.153582,0.027103,0.397507,0.180685,0.045171,0.018068,0.271027
event_t,0.027103,0.036137,0.027103,0.018068,0.063240,0.126479,0.009034,0.000000,0.081308
location_t,0.162616,0.054205,0.225856,0.081308,0.442678,0.243924,0.072274,0.018068,0.343301
movement_t,0.045171,0.000000,0.018068,0.036137,0.027103,0.054205,0.000000,0.018068,0.000000
organization_t,0.496883,0.081308,0.596260,0.045171,2.610895,0.785979,0.298130,0.171651,1.002801
person_t,0.542054,0.099377,0.560123,0.081308,1.237691,0.000000,0.280061,0.117445,0.740808
political_organization_t,0.036137,0.000000,0.090342,0.009034,0.144548,0.099377,0.090342,0.000000,0.063240
vessel_t,0.018068,0.000000,0.063240,0.000000,0.153582,0.081308,0.000000,0.108411,0.054205
unknown_t,0.433644,0.036137,0.316198,0.009034,1.282862,0.731773,0.063240,0.054205,0.740808

In [68]:
# 比例
o_table_4points=(o_table_4points/11069) * 100
o_table_4points

,company_s,event_s,location_s,movement_s,organization_s,person_s,political_organization_s,vessel_s,unknown_s
company_t,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000
event_t,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000
location_t,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000
movement_t,NaN,NaN,NaN,NaN,0.009034,NaN,NaN,NaN,0.000000
organization_t,0.009034,0.0,0.018068,0.0,0.054205,0.027103,0.009034,0.009034,0.018068
person_t,NaN,NaN,NaN,NaN,0.036137,NaN,NaN,NaN,0.009034
political_organization_t,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000
vessel_t,NaN,NaN,NaN,NaN,0.009034,NaN,NaN,NaN,0.000000
unknown_t,0.0,0.0,0.0,0.0,0.045171,0.0,0.0,0.0,0.000000

# Partnership

In [69]:
arr3 = np.zeros((9,9))

p_table=pd.DataFrame(arr3, columns=['company_s', 'event_s', 'location_s', 'movement_s', 'organization_s', 'person_s', 'political_organization_s', 'vessel_s', 'unknown_s'],index=['company_t', 'event_t', 'location_t', 'movement_t', 'organization_t', 'person_t', 'political_organization_t', 'vessel_t', 'unknown_t'])

p_table_4points=pd.DataFrame( columns=['company_s', 'event_s', 'location_s', 'movement_s', 'organization_s', 'person_s', 'political_organization_s', 'vessel_s', 'unknown_s'],index=['company_t', 'event_t', 'location_t', 'movement_t', 'organization_t', 'person_t', 'political_organization_t', 'vessel_t', 'unknown_t'])
p_table_4points['organization_s'] = 0
p_table_4points['unknown_s'] = 0
p_table_4points.iloc[4] = 0
p_table_4points.iloc[8] = 0

p_cnt = 0

In [70]:
collect_4points = pd.DataFrame()
for row in df.iterrows():
    # print(row[1][1],row[1][7],row[1][9])
    if row[1][1] == 'partnership':
        p_cnt = p_cnt + 1
        p_table[row[1][7]+'_s'][row[1][9]+'_t'] = p_table[row[1][7]+'_s'][row[1][9]+'_t'] + 1

        if (row[1][4] == 'Mar de la Vida OJSC') or (row[1][5] == 'Mar de la Vida OJSC') or (row[1][4] == '979893388') or (row[1][5] == '979893388') or (row[1][4] == 'Oceanfront Oasis Inc Carriers') or (row[1][5] == 'Oceanfront Oasis Inc Carriers') or (row[1][4] == '8327') or (row[1][5] == '8327'):
            collect_4points = collect_4points.append(row[1])
            p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1

collect_4points

/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/2151726921.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = p_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1

,Unnamed: 0,link_type,weight,dataset_x,source,target,key,source_type,source_country,target_type,target_country
177,177,partnership,0.855847,MC1,Faroe Islands Shrimp Shark,979893388,0,company,Rio Isla,organization,NaN
777,777,partnership,0.860494,MC1,69150209,979893388,0,organization,NaN,organization,NaN
866,866,partnership,0.831708,MC1,Maria Mitchell,979893388,0,person,Oceanus,organization,NaN
1095,1095,partnership,0.836273,MC1,6731,979893388,0,organization,NaN,organization,NaN
1142,1142,partnership,0.880474,MC1,665,979893388,0,organization,NaN,organization,NaN
2414,2414,partnership,0.857494,MC1,8327,185106,0,organization,NaN,organization,NaN
2422,2422,partnership,0.900931,MC1,8327,Calvin Salas,0,organization,NaN,person,Marebak
2594,2594,partnership,0.837715,MC1,9786,979893388,0,organization,NaN,organization,NaN
4533,4533,partnership,0.819067,MC1,Kelly Brown,979893388,0,person,Country_198078,organization,NaN
4961,4961,partnership,0.901047,MC1,979893388,months,0,organization,NaN,movement,NaN
4966,4966,partnership,0.866931,MC1,979893388,98703,0,organization,NaN,organization,NaN
4967,4967,partnership,0.852776,MC1,979893388,Dana Goodwin,0,organization,NaN,person,Marebak
4968,4968,partnership,0.854423,MC1,979893388,567,0,organization,NaN,organization,NaN
4970,4970,partnership,0.838082,MC1,979893388,23,0,organization,NaN,organization,NaN
4974,4974,partnership,0.831604,MC1,979893388,ARA Contraalmirante Cordero,0,organization,NaN,vessel,NaN
4982,4982,partnership,0.816541,MC1,979893388,418382,0,organization,NaN,organization,NaN
4983,4983,partnership,0.827533,MC1,979893388,16927047,0,organization,NaN,organization,NaN
4984,4984,partnership,0.856693,MC1,979893388,30041,0,organization,NaN,organization,NaN
4985,4985,partnership,0.864877,MC1,979893388,6471708,0,organization,NaN,organization,NaN
4986,4986,partnership,0.833301,MC1,979893388,520673,0,organization,NaN,organization,NaN
4987,4987,partnership,0.810879,MC1,979893388,565431,0,organization,NaN,organization,NaN
4988,4988,partnership,0.928481,MC1,979893388,Benton Ltd. Liability Co,0,organization,NaN,company,Country_271835
4989,4989,partnership,0.855360,MC1,979893388,ninety,0,organization,NaN,movement,NaN
4990,4990,partnership,0.899304,MC1,979893388,dup90,0,organization,NaN,event,NaN
4991,4991,partnership,0.945531,MC1,979893388,days,0,organization,NaN,movement,NaN
4992,4992,partnership,0.822198,MC1,979893388,sh rn y Corporation,0,organization,NaN,unknown,NaN
4993,4993,partnership,0.933341,MC1,979893388,822596165,0,organization,NaN,organization,NaN
4994,4994,partnership,0.969303,MC1,979893388,5421,0,organization,NaN,organization,NaN
4995,4995,partnership,0.867280,MC1,979893388,2913,0,organization,NaN,organization,NaN
4996,4996,partnership,0.909865,MC1,979893388,Pez Dorado BV Logistics,0,organization,NaN,company,Country_271835
4997,4997,partnership,0.901353,MC1,979893388,019d89a8-36be-4402-bf3c-d13cb982cf3f,0,organization,NaN,location,NaN
5005,5005,partnership,0.937897,MC1,979893388,57,0,organization,NaN,political_organization,NaN
5006,5006,partnership,0.959120,MC1,979893388,Luis Jones,0,organization,NaN,person,Riodelsol
5007,5007,partnership,0.908736,MC1,979893388,c01c6a10-60c9-4f11-9409-aa04c3963826,0,organization,NaN,location,NaN
5008,5008,partnership,0.935585,MC1,979893388,17232,0,organization,NaN,political_organization,NaN
5009,5009,partnership,0.886883,MC1,979893388,Derek Burke,0,organization,NaN,person,Nalakond
5032,5032,partnership,0.801267,MC1,979893388,20370602035941,0,organization,NaN,unknown,NaN
5362,5362,partnership,0.834555,MC1,6335187,979893388,0,organization,NaN,organization,NaN
6897,6897,partnership,0.866446,MC1,58877070,979893388,0,organization,NaN,organization,NaN
7058,7058,partnership,0.841500,MC1,Lisa Rocha,979893388,0,person,Quandarix,organization,NaN
7294,7294,partnership,0.957123,MC1,6f59e8d7-8f5d-4a7d-a3a4-50ddcb7ad9ad,979893388,0,location,NaN,organization,NaN
7375,7375,partnership,0.851147,MC1,542341,979893388,0,organization,NaN,organization,NaN
8038,8038,partnership,0.812323,MC1,Kevin Burnett,Mar de la Vida OJSC,0,person,Country_271835,unknown,NaN
8040,8040,partnership,0.802768,MC1,decfc924-5bdc-4fba-8bbd-bb57d8d478d9,Mar de la Vida OJSC,0,location,NaN,unknown,NaN
8267,8267,partnership,0.896930,MC1,6070651,979893388,0,organization,NaN,organization,NaN
8300,8300,partnership,0.900007,MC1,c01c6a10-60c9-4f11-9409-aa04c3963826,979893388,0,location,NaN,organization,NaN
8317,8317,partnership,0.881707,MC1,156,979893388,0,political_organization,NaN,organization,NaN
8325,8325,partnership,0.868431,MC1,1eb512b7-c4ce-4b7e-9965-2236bf1afc9e,979893388,0,location,NaN,organization,NaN
10379,10379,partnership,0.909512,MC1,Estrella de Coral Ltd. Corporation Logistics,979893388,0,unknown,NaN,organization,NaN
10468,10468,partnership,0.884882,MC1,Mar de la Vida OJSC,Kevin Burnett,0,unknown,NaN,person,Country_271835
10470,10470,partnership,0.882215,MC1,Mar de la Vida OJSC,Rebecca Walker,0,unknown,NaN,person,Country_271835

In [71]:
# 个数
p_table

,company_s,event_s,location_s,movement_s,organization_s,person_s,political_organization_s,vessel_s,unknown_s
company_t,11.0,2.0,14.0,2.0,68.0,30.0,3.0,4.0,24.0
event_t,5.0,4.0,10.0,1.0,22.0,33.0,2.0,0.0,5.0
location_t,10.0,0.0,17.0,2.0,49.0,28.0,12.0,8.0,18.0
movement_t,6.0,1.0,6.0,3.0,10.0,2.0,0.0,0.0,1.0
organization_t,74.0,4.0,58.0,1.0,459.0,121.0,31.0,11.0,112.0
person_t,40.0,8.0,68.0,4.0,182.0,0.0,19.0,14.0,109.0
political_organization_t,2.0,1.0,14.0,0.0,41.0,25.0,8.0,1.0,7.0
vessel_t,2.0,1.0,5.0,0.0,25.0,10.0,0.0,10.0,9.0
unknown_t,43.0,9.0,42.0,4.0,123.0,91.0,10.0,13.0,693.0

In [72]:
# 个数
p_table_4points

,company_s,event_s,location_s,movement_s,organization_s,person_s,political_organization_s,vessel_s,unknown_s
company_t,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,0
event_t,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,0
location_t,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,0
movement_t,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,0
organization_t,1,0,3,0,21,3,1,0,1
person_t,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,2
political_organization_t,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,0
vessel_t,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,0
unknown_t,0,0,1,0,2,1,0,0,0

In [73]:
# 总数
print(p_cnt)

2917

In [74]:
# 比例
p_table=(p_table/11069) * 100
p_table

,company_s,event_s,location_s,movement_s,organization_s,person_s,political_organization_s,vessel_s,unknown_s
company_t,0.099377,0.018068,0.126479,0.018068,0.614328,0.271027,0.027103,0.036137,0.216822
event_t,0.045171,0.036137,0.090342,0.009034,0.198753,0.298130,0.018068,0.000000,0.045171
location_t,0.090342,0.000000,0.153582,0.018068,0.442678,0.252959,0.108411,0.072274,0.162616
movement_t,0.054205,0.009034,0.054205,0.027103,0.090342,0.018068,0.000000,0.000000,0.009034
organization_t,0.668534,0.036137,0.523986,0.009034,4.146716,1.093143,0.280061,0.099377,1.011835
person_t,0.361370,0.072274,0.614328,0.036137,1.644232,0.000000,0.171651,0.126479,0.984732
political_organization_t,0.018068,0.009034,0.126479,0.000000,0.370404,0.225856,0.072274,0.009034,0.063240
vessel_t,0.018068,0.009034,0.045171,0.000000,0.225856,0.090342,0.000000,0.090342,0.081308
unknown_t,0.388472,0.081308,0.379438,0.036137,1.111211,0.822116,0.090342,0.117445,6.260728

In [75]:
# 比例
p_table_4points=(p_table_4points/11069) * 100
p_table_4points

,company_s,event_s,location_s,movement_s,organization_s,person_s,political_organization_s,vessel_s,unknown_s
company_t,NaN,NaN,NaN,NaN,0.018068,NaN,NaN,NaN,0.000000
event_t,NaN,NaN,NaN,NaN,0.009034,NaN,NaN,NaN,0.000000
location_t,NaN,NaN,NaN,NaN,0.018068,NaN,NaN,NaN,0.000000
movement_t,NaN,NaN,NaN,NaN,0.027103,NaN,NaN,NaN,0.000000
organization_t,0.009034,0.0,0.027103,0.0,0.189719,0.027103,0.009034,0.0,0.009034
person_t,NaN,NaN,NaN,NaN,0.036137,NaN,NaN,NaN,0.018068
political_organization_t,NaN,NaN,NaN,NaN,0.018068,NaN,NaN,NaN,0.000000
vessel_t,NaN,NaN,NaN,NaN,0.009034,NaN,NaN,NaN,0.000000
unknown_t,0.0,0.0,0.009034,0.0,0.018068,0.009034,0.0,0.0,0.000000

# Membership

In [76]:
arr5 = np.zeros((9,9))

m_table=pd.DataFrame(arr5, columns=['company_s', 'event_s', 'location_s', 'movement_s', 'organization_s', 'person_s', 'political_organization_s', 'vessel_s', 'unknown_s'],index=['company_t', 'event_t', 'location_t', 'movement_t', 'organization_t', 'person_t', 'political_organization_t', 'vessel_t', 'unknown_t'])

m_table_4points=pd.DataFrame( columns=['company_s', 'event_s', 'location_s', 'movement_s', 'organization_s', 'person_s', 'political_organization_s', 'vessel_s', 'unknown_s'],index=['company_t', 'event_t', 'location_t', 'movement_t', 'organization_t', 'person_t', 'political_organization_t', 'vessel_t', 'unknown_t'])

m_table_4points['organization_s'] = 0
m_table_4points['unknown_s'] = 0
m_table_4points.iloc[4] = 0
m_table_4points.iloc[8] = 0

m_cnt = 0

In [77]:
collect_4points = pd.DataFrame()
for row in df.iterrows():
    # print(row[1][1],row[1][7],row[1][9])
    if row[1][1] == 'membership':
        m_cnt = m_cnt + 1
        m_table[row[1][7]+'_s'][row[1][9]+'_t'] = m_table[row[1][7]+'_s'][row[1][9]+'_t'] + 1

        if (row[1][4] == 'Mar de la Vida OJSC') or (row[1][5] == 'Mar de la Vida OJSC') or (row[1][4] == '979893388') or (row[1][5] == '979893388') or (row[1][4] == 'Oceanfront Oasis Inc Carriers') or (row[1][5] == 'Oceanfront Oasis Inc Carriers') or (row[1][4] == '8327') or (row[1][5] == '8327'):
            collect_4points = collect_4points.append(row[1])
            m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1

collect_4points

/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = m_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/739606551.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

,Unnamed: 0,link_type,weight,dataset_x,source,target,key,source_type,source_country,target_type,target_country
1249,1249,membership,0.901995,MC1,435054320,8327,0,organization,NaN,organization,NaN
1693,1693,membership,0.854808,MC1,png xi Line,979893388,0,company,Country_628643,organization,NaN
1954,1954,membership,0.826960,MC1,April,979893388,0,event,NaN,organization,NaN
1991,1991,membership,0.803921,MC1,Jennifer Alvarez,979893388,0,person,Oceanus,organization,NaN
2114,2114,membership,0.806434,MC1,Stephanie Hinton,979893388,0,person,Oceanus,organization,NaN
...,...,...,...,...,...,...,...,...,...,...,...
10476,10476,membership,0.910024,MC1,Mar de la Vida OJSC,33681303,0,unknown,NaN,organization,NaN
10477,10477,membership,0.936195,MC1,Mar de la Vida OJSC,60017,0,unknown,NaN,organization,NaN
10479,10479,membership,0.933502,MC1,Mar de la Vida OJSC,Ancla Azul Company Solutions,0,unknown,NaN,unknown,NaN
10736,10736,membership,0.885812,MC1,Forwading S.A. de C.V.,979893388,0,unknown,NaN,organization,NaN
10878,10878,membership,0.898833,MC1,âUS,979893388,0,unknown,NaN,organization,NaN

In [78]:
# 个数
m_table

,company_s,event_s,location_s,movement_s,organization_s,person_s,political_organization_s,vessel_s,unknown_s
company_t,31.0,6.0,52.0,2.0,104.0,48.0,9.0,8.0,56.0
event_t,8.0,5.0,12.0,4.0,24.0,32.0,3.0,0.0,23.0
location_t,31.0,7.0,61.0,3.0,75.0,55.0,17.0,9.0,56.0
movement_t,5.0,0.0,6.0,0.0,9.0,9.0,0.0,2.0,5.0
organization_t,88.0,17.0,116.0,8.0,408.0,144.0,55.0,13.0,183.0
person_t,65.0,19.0,129.0,5.0,268.0,0.0,37.0,20.0,220.0
political_organization_t,3.0,2.0,17.0,0.0,33.0,21.0,18.0,1.0,10.0
vessel_t,16.0,0.0,4.0,1.0,40.0,16.0,0.0,9.0,17.0
unknown_t,83.0,12.0,96.0,4.0,260.0,155.0,42.0,12.0,333.0

In [79]:
# 个数
m_table_4points

,company_s,event_s,location_s,movement_s,organization_s,person_s,political_organization_s,vessel_s,unknown_s
company_t,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,0
event_t,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,1
location_t,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,0
movement_t,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0
organization_t,5,2,2,0,22,12,5,0,12
person_t,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,3
political_organization_t,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0
vessel_t,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,0
unknown_t,0,0,0,0,7,0,1,0,2

In [80]:
# 总数
print(m_cnt)

3777

In [81]:
# 比例
m_table=(m_table/11069) * 100
m_table

,company_s,event_s,location_s,movement_s,organization_s,person_s,political_organization_s,vessel_s,unknown_s
company_t,0.280061,0.054205,0.469780,0.018068,0.939561,0.433644,0.081308,0.072274,0.505917
event_t,0.072274,0.045171,0.108411,0.036137,0.216822,0.289096,0.027103,0.000000,0.207788
location_t,0.280061,0.063240,0.551089,0.027103,0.677568,0.496883,0.153582,0.081308,0.505917
movement_t,0.045171,0.000000,0.054205,0.000000,0.081308,0.081308,0.000000,0.018068,0.045171
organization_t,0.795013,0.153582,1.047972,0.072274,3.685970,1.300931,0.496883,0.117445,1.653266
person_t,0.587226,0.171651,1.165417,0.045171,2.421176,0.000000,0.334267,0.180685,1.987533
political_organization_t,0.027103,0.018068,0.153582,0.000000,0.298130,0.189719,0.162616,0.009034,0.090342
vessel_t,0.144548,0.000000,0.036137,0.009034,0.361370,0.144548,0.000000,0.081308,0.153582
unknown_t,0.749842,0.108411,0.867287,0.036137,2.348902,1.400307,0.379438,0.108411,3.008402

In [82]:
# 比例
m_table_4points=(m_table_4points/11069) * 100
m_table_4points

,company_s,event_s,location_s,movement_s,organization_s,person_s,political_organization_s,vessel_s,unknown_s
company_t,NaN,NaN,NaN,NaN,0.009034,NaN,NaN,NaN,0.000000
event_t,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.009034
location_t,NaN,NaN,NaN,NaN,0.009034,NaN,NaN,NaN,0.000000
movement_t,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000
organization_t,0.045171,0.018068,0.018068,0.0,0.198753,0.108411,0.045171,0.0,0.108411
person_t,NaN,NaN,NaN,NaN,0.090342,NaN,NaN,NaN,0.027103
political_organization_t,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000
vessel_t,NaN,NaN,NaN,NaN,0.009034,NaN,NaN,NaN,0.000000
unknown_t,0.0,0.0,0.0,0.0,0.063240,0.0,0.009034,0.0,0.018068

# Family_relationship

In [83]:
arr7 = np.zeros((9,9))

f_table=pd.DataFrame(arr7, columns=['company_s', 'event_s', 'location_s', 'movement_s', 'organization_s', 'person_s', 'political_organization_s', 'vessel_s', 'unknown_s'],index=['company_t', 'event_t', 'location_t', 'movement_t', 'organization_t', 'person_t', 'political_organization_t', 'vessel_t', 'unknown_t'])

f_table_4points=pd.DataFrame(columns=['company_s', 'event_s', 'location_s', 'movement_s', 'organization_s', 'person_s', 'political_organization_s', 'vessel_s', 'unknown_s'],index=['company_t', 'event_t', 'location_t', 'movement_t', 'organization_t', 'person_t', 'political_organization_t', 'vessel_t', 'unknown_t'])
f_table_4points['organization_s'] = 0
f_table_4points['unknown_s'] = 0
f_table_4points.iloc[4] = 0
f_table_4points.iloc[8] = 0

f_cnt = 0

In [84]:
collect_4points = pd.DataFrame()
for row in df.iterrows():
    # print(row[1][1],row[1][7],row[1][9])
    if row[1][1] == 'family_relationship':
        f_cnt = f_cnt + 1
        f_table[row[1][7]+'_s'][row[1][9]+'_t'] = f_table[row[1][7]+'_s'][row[1][9]+'_t'] + 1

        if (row[1][4] == 'Mar de la Vida OJSC') or (row[1][5] == 'Mar de la Vida OJSC') or (row[1][4] == '979893388') or (row[1][5] == '979893388') or (row[1][4] == 'Oceanfront Oasis Inc Carriers') or (row[1][5] == 'Oceanfront Oasis Inc Carriers') or (row[1][4] == '8327') or (row[1][5] == '8327'):
            collect_4points = collect_4points.append(row[1])
            f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1

collect_4points

/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  collect_4points = collect_4points.append(row[1])
/var/folders/rw/kvt1fn_n0h951yj9_wjsc5wm0000gn/T/ipykernel_60729/1248081312.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] = f_table_4points[row[1][7]+'_s'][row[1][9]+'_t'] + 1

,Unnamed: 0,link_type,weight,dataset_x,source,target,key,source_type,source_country,target_type,target_country
437,437,family_relationship,0.863973,MC1,4,979893388,0,organization,NaN,organization,NaN
471,471,family_relationship,0.856004,MC1,196159,979893388,0,organization,NaN,organization,NaN
582,582,family_relationship,0.870096,MC1,9067,979893388,0,organization,NaN,organization,NaN
601,601,family_relationship,0.847895,MC1,750975,979893388,0,organization,NaN,organization,NaN
602,602,family_relationship,0.858981,MC1,750975,979893388,1,organization,NaN,organization,NaN
...,...,...,...,...,...,...,...,...,...,...,...
10497,10497,family_relationship,0.883705,MC1,Seafood,979893388,0,unknown,NaN,organization,NaN
10513,10513,family_relationship,0.831505,MC1,Caribbean,979893388,0,unknown,NaN,organization,NaN
10587,10587,family_relationship,0.868569,MC1,âCompliance,979893388,0,unknown,NaN,organization,NaN
10946,10946,family_relationship,0.830367,MC1,Lake Tanganyika Sea AS Shipping,979893388,0,unknown,NaN,organization,NaN
10977,10977,family_relationship,0.904092,MC1,MV,979893388,0,unknown,NaN,organization,NaN

In [85]:
# 个数
f_table

,company_s,event_s,location_s,movement_s,organization_s,person_s,political_organization_s,vessel_s,unknown_s
company_t,12.0,1.0,14.0,1.0,78.0,22.0,3.0,2.0,31.0
event_t,1.0,0.0,1.0,1.0,9.0,7.0,1.0,0.0,1.0
location_t,20.0,2.0,18.0,2.0,61.0,13.0,6.0,4.0,29.0
movement_t,1.0,0.0,3.0,0.0,4.0,2.0,0.0,1.0,4.0
organization_t,50.0,6.0,47.0,1.0,211.0,46.0,20.0,6.0,66.0
person_t,23.0,4.0,31.0,5.0,98.0,920.0,12.0,10.0,58.0
political_organization_t,2.0,0.0,5.0,0.0,16.0,3.0,2.0,0.0,7.0
vessel_t,4.0,0.0,9.0,0.0,13.0,8.0,0.0,3.0,3.0
unknown_t,33.0,4.0,26.0,1.0,87.0,31.0,10.0,3.0,156.0

In [86]:
# 个数
f_table_4points

,company_s,event_s,location_s,movement_s,organization_s,person_s,political_organization_s,vessel_s,unknown_s
company_t,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,0
event_t,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0
location_t,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,1
movement_t,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0
organization_t,1,0,7,0,22,9,1,0,10
person_t,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,0
political_organization_t,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0
vessel_t,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0
unknown_t,0,0,0,0,10,0,0,0,1

In [87]:
# 总数
print(f_cnt)

2395

In [88]:
# 比例
f_table=(f_table/11069) * 100
f_table

,company_s,event_s,location_s,movement_s,organization_s,person_s,political_organization_s,vessel_s,unknown_s
company_t,0.108411,0.009034,0.126479,0.009034,0.704671,0.198753,0.027103,0.018068,0.280061
event_t,0.009034,0.000000,0.009034,0.009034,0.081308,0.063240,0.009034,0.000000,0.009034
location_t,0.180685,0.018068,0.162616,0.018068,0.551089,0.117445,0.054205,0.036137,0.261993
movement_t,0.009034,0.000000,0.027103,0.000000,0.036137,0.018068,0.000000,0.009034,0.036137
organization_t,0.451712,0.054205,0.424609,0.009034,1.906225,0.415575,0.180685,0.054205,0.596260
person_t,0.207788,0.036137,0.280061,0.045171,0.885355,8.311501,0.108411,0.090342,0.523986
political_organization_t,0.018068,0.000000,0.045171,0.000000,0.144548,0.027103,0.018068,0.000000,0.063240
vessel_t,0.036137,0.000000,0.081308,0.000000,0.117445,0.072274,0.000000,0.027103,0.027103
unknown_t,0.298130,0.036137,0.234890,0.009034,0.785979,0.280061,0.090342,0.027103,1.409341

In [89]:
# 比例
f_table_4points=(f_table_4points/11069) * 100
f_table_4points

,company_s,event_s,location_s,movement_s,organization_s,person_s,political_organization_s,vessel_s,unknown_s
company_t,NaN,NaN,NaN,NaN,0.045171,NaN,NaN,NaN,0.000000
event_t,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000
location_t,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.009034
movement_t,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000
organization_t,0.009034,0.0,0.06324,0.0,0.198753,0.081308,0.009034,0.0,0.090342
person_t,NaN,NaN,NaN,NaN,0.063240,NaN,NaN,NaN,0.000000
political_organization_t,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000
vessel_t,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000
unknown_t,0.0,0.0,0.0,0.0,0.090342,0.0,0.0,0.0,0.009034